bug:
  - changed-files:
      - any-glob-to-any-file: "server/**"
      - any-glob-to-any-file: "client/**"
      - any-glob-to-any-file: "android/**"
      - any-glob-to-any-file: "ios/**"

enhancement:
  - changed-files:
      - any-glob-to-any-file: "client/**"
      - any-glob-to-any-file: "android/**"
      - any-glob-to-any-file: "ios/**"
      - any-glob-to-any-file: "docs/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "README.md"
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: ".github/**/*.md"

workflow:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
      - any-glob-to-any-file: ".github/*.yml"
