#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════
   generate-sitemap.js — write client/public/sitemap.xml from
   the URL list in scripts/indexnow-urls.js.

   <lastmod> comes from the last git commit that touched each
   page's source file, so the dates reflect reality instead of
   whatever someone remembered to type. Pages with uncommitted
   changes, or that git doesn't know about yet, fall back to
   today.

     node scripts/generate-sitemap.js          # write the file
     node scripts/generate-sitemap.js --check  # CI: fail if stale

   Re-run after adding a public page or editing one's content.
═════════════════════════════════════════════════════════════════ */

'use strict';

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const { PUBLIC_PAGES, publicOrigin } = require('./indexnow-urls');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'client', 'public', 'sitemap.xml');

function today() {
  return new Date().toISOString().slice(0, 10);
}

/* Last commit date (YYYY-MM-DD) for a client page, or today if
   git has nothing to say about it. */
function lastModified(file) {
  const rel = path.join('client', file);
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', rel], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : today();
  } catch {
    return today();
  }
}

function buildXml() {
  const origin = publicOrigin();
  const entries = PUBLIC_PAGES.map((p) => {
    const loc = p.path === '/' ? `${origin}/` : `${origin}${p.path}`;
    return [
      '  <url>',
      `    <loc>${loc}</loc>`,
      `    <lastmod>${lastModified(p.file)}</lastmod>`,
      `    <changefreq>${p.changefreq}</changefreq>`,
      `    <priority>${p.priority}</priority>`,
      '  </url>',
    ].join('\n');
  });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/generate-sitemap.js — do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    '</urlset>',
    '',
  ].join('\n');
}

function main() {
  const xml = buildXml();
  const check = process.argv.includes('--check');
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';

  if (check) {
    if (current !== xml) {
      console.error('sitemap.xml is out of date — run `npm run sitemap`.');
      process.exit(1);
    }
    console.log(`sitemap.xml is current (${PUBLIC_PAGES.length} URLs).`);
    return;
  }

  fs.writeFileSync(OUT, xml);
  console.log(`Wrote ${path.relative(ROOT, OUT)} — ${PUBLIC_PAGES.length} URLs.`);
}

main();
