#!/usr/bin/env node
'use strict';

/**
 * release-check.js — Fail the build if a commit message, file header, or
 * generated doc contains an AI signature or co-author trailer.
 *
 * Usage:
 *   node scripts/release-check.js              # check everything
 *   node scripts/release-check.js --commits    # check commit messages only
 *   node scripts/release-check.js --headers    # check file headers only
 *   node scripts/release-check.js --docs       # check generated docs only
 *   node scripts/release-check.js --help       # show usage
 *
 * What it checks:
 *   1. COMMIT MESSAGES — the last N commits on the current branch for:
 *      - "Co-authored-by: ..." trailers where the author looks like an AI
 *        (Claude, ChatGPT, GPT, Gemini, Copilot, etc.)
 *      - "Generated with ..." or "Generated by ..." markers
 *      - "AI-generated" or similar signatures in the commit body
 *
 *   2. FILE HEADERS — source files for:
 *      - Block comments containing "generated by Claude", "generated by AI",
 *        "generated with ChatGPT", etc.
 *      - File headers that claim AI authorship
 *
 *   3. GENERATED DOCS — auto-generated files for:
 *      - AI signature lines in changelog.html, changelog.md, sitemap.xml, etc.
 *      - "Generated with AI" markers in generated artifacts
 *
 * The script exits 0 on success, 1 on failure.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');

// Patterns that indicate AI involvement in a way that shouldn't be in
// release commits, file headers, or generated docs.
const AI_SIGNATURE_PATTERNS = [
  // Co-author trailers from AI tools
  { pattern: /Co-authored-by:\s*(?:Claude|ChatGPT|GPT|Gemini|Copilot|Bard|AI|Assistant)\b/i, label: 'AI co-author trailer' },
  { pattern: /co-authored-by:\s*[<][^>]*[Cc]laude[^>]*[>]/i, label: 'Claude co-author' },
  { pattern: /co-authored-by:\s*[<][^>]*[Cc]hat[Gg]pt[^>]*[>]/i, label: 'ChatGPT co-author' },
  { pattern: /co-authored-by:\s*[<][^>]*[Gg]emini[^>]*[>]/i, label: 'Gemini co-author' },

  // Generated-by markers
  { pattern: /generated\s+(?:with|by)\s+(?:Claude|ChatGPT|GPT|Gemini|Copilot|AI|an?\s+AI|code\s+generation)/i, label: 'AI generation marker' },
  { pattern: /generated\s+by\s+(?:Claude|ChatGPT|GPT|Gemini|Copilot)/i, label: 'AI generator attribution' },

  // AI signature lines
  { pattern: /AI-generated/i, label: 'AI-generated marker' },
  { pattern: /generated\s+by\s+AI/i, label: 'AI generation attribution' },

  // Tool-specific signatures
  { pattern: /Claude\s+Artifacts/i, label: 'Claude Artifacts marker' },
  { pattern: /created\s+by\s+Claude/i, label: 'Claude creation marker' },
];

// File patterns that should be checked for headers
const HEADER_CHECK_PATTERNS = [
  /\.(kt|kts|swift|js|ts|py|rb|go|rs|java|scala|sh|bash|zsh)$/i,  // Source files
  /\.(md|txt|rst|adoc)$/i,  // Documentation
];

// Generated doc files that should be checked
const GENERATED_DOC_PATHS = [
  'client/public/changelog.md',
  'client/changelog.html',
  'client/public/sitemap.xml',
  'client/public/robots.txt',
  'docs/release-notes/README.md',
];

// Number of commits to check
const COMMITS_TO_CHECK = 50;

function printUsage() {
  console.log(`
release-check.js — Fail the build if commits, headers, or docs contain AI signatures

Usage:
  node scripts/release-check.js              # Check everything (default)
  node scripts/release-check.js --commits    # Check commit messages only
  node scripts/release-check.js --headers    # Check file headers only
  node scripts/release-check.js --docs       # Check generated docs only
  node scripts/release-check.js --help       # Show this help

What it checks:
  --commits   Last ${COMMITS_TO_CHECK} commit messages for AI co-author trailers
              and generation markers
  --headers   Source file headers for AI-generated markers
  --docs      Generated documentation for AI signatures

Exit codes:
  0 — No AI signatures found
  1 — AI signatures found (or error running checks)
`);
}

function run(cmd, opts = {}) {
  try {
    return execSync(cmd, {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      ...opts,
    }).trim();
  } catch (e) {
    return null;
  }
}

function checkCommitMessages() {
  console.log('Checking commit messages for AI signatures...\n');

  const logOutput = run(`git log -${COMMITS_TO_CHECK} --format='%H||%s||%b||%b'`, { maxBuffer: 10 * 1024 * 1024 });
  if (!logOutput) {
    console.log('  ⚠ Could not read commit history — skipping commit check');
    return [];
  }

  const failures = [];
  const commits = logOutput.split('%n').filter(Boolean);

  // git log format with %n for newlines is tricky; use a different approach
  const rawLog = run(`git log -${COMMITS_TO_CHECK} --format=%H%n---COMMIT---`, { maxBuffer: 10 * 1024 * 1024 });
  if (!rawLog) return [];

  const commitHashes = rawLog.split('---COMMIT---').filter(Boolean);
  let idx = 0;

  for (const hash of commitHashes) {
    const hashTrimmed = hash.trim();
    if (!hashTrimmed) continue;

    const msg = run(`git log -1 --format=%s ${hashTrimmed}`);
    const body = run(`git log -1 --format=%b ${hashTrimmed}`);

    if (!msg && !body) continue;

    const fullText = `${msg}\n${body}`.toLowerCase();

    for (const { pattern, label } of AI_SIGNATURE_PATTERNS) {
      if (pattern.test(fullText)) {
        failures.push({
          type: 'commit',
          hash: hashTrimmed.slice(0, 7),
          label,
          message: msg ? msg.slice(0, 80) : '(no subject)',
        });
        break; // One failure per commit is enough
      }
    }

    idx++;
  }

  if (failures.length) {
    console.log(`  ❌ Found ${failures.length} commit(s) with AI signatures:\n`);
    for (const f of failures) {
      console.log(`    Commit ${f.hash}: ${f.label}`);
      console.log(`      "${f.message}"\n`);
    }
  } else {
    console.log(`  ✅ No AI signatures in last ${COMMITS_TO_CHECK} commits\n`);
  }

  return failures;
}

function checkFileHeaders() {
  console.log('Checking file headers for AI signatures...\n');

  const failures = [];

  // Find all files that match our patterns
  const findCmd = 'find . -type f \\( -name "*.kt" -o -name "*.kts" -o -name "*.swift" -o -name "*.js" -o -name "*.ts" -o -name "*.py" -o -name "*.sh" -o -name "*.md" \\) -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./dist/*"';
  const files = run(findCmd);

  if (!files) {
    console.log('  ⚠ Could not find files — skipping header check');
    return [];
  }

  const fileList = files.split('\n').filter(Boolean);

  for (const file of fileList) {
    const absPath = path.resolve(ROOT, file);
    if (!fs.existsSync(absPath)) continue;

    try {
      const content = fs.readFileSync(absPath, 'utf8');
      const first800 = content.slice(0, 800); // Check first 800 chars for headers

      for (const { pattern, label } of AI_SIGNATURE_PATTERNS) {
        if (pattern.test(first800)) {
          failures.push({
            type: 'header',
            file: file,
            label,
            line: content.slice(0, 200).split('\n').findIndex((line) => pattern.test(line)) + 1,
          });
          break;
        }
      }
    } catch {
      // Skip files we can't read
    }
  }

  if (failures.length) {
    console.log(`  ❌ Found ${failures.length} file(s) with AI signatures in headers:\n`);
    for (const f of failures) {
      console.log(`    ${f.file}: ${f.label}${f.line ? ` (line ~${f.line})` : ''}\n`);
    }
  } else {
    console.log(`  ✅ No AI signatures in file headers\n`);
  }

  return failures;
}

function checkGeneratedDocs() {
  console.log('Checking generated docs for AI signatures...\n');

  const failures = [];

  for (const docPath of GENERATED_DOC_PATHS) {
    const absPath = path.resolve(ROOT, docPath);
    if (!fs.existsSync(absPath)) continue;

    try {
      const content = fs.readFileSync(absPath, 'utf8');

      for (const { pattern, label } of AI_SIGNATURE_PATTERNS) {
        if (pattern.test(content)) {
          // Find the line number
          const lineNum = content.split('\n').findIndex((line) => pattern.test(line)) + 1;
          failures.push({
            type: 'doc',
            file: docPath,
            label,
            line: lineNum,
          });
          break;
        }
      }
    } catch {
      // Skip files we can't read
    }
  }

  if (failures.length) {
    console.log(`  ❌ Found ${failures.length} generated doc(s) with AI signatures:\n`);
    for (const f of failures) {
      console.log(`    ${f.file}: ${f.label}${f.line ? ` (line ${f.line})` : ''}\n`);
    }
  } else {
    console.log(`  ✅ No AI signatures in generated docs\n`);
  }

  return failures;
}

function main() {
  const args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    printUsage();
    process.exit(0);
  }

  const checkCommits = args.includes('--commits') || !args.some((a) => ['--commits', '--headers', '--docs'].includes(a));
  const checkHeaders = args.includes('--headers') || !args.some((a) => ['--commits', '--headers', '--docs'].includes(a));
  const checkDocs = args.includes('--docs') || !args.some((a) => ['--commits', '--headers', '--docs'].includes(a));

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  FiHaven Release Check — AI Signature Scanner');
  console.log('═══════════════════════════════════════════════════════════════\n');

  const allFailures = [];

  if (checkCommits) {
    allFailures.push(...checkCommitMessages());
  }

  if (checkHeaders) {
    allFailures.push(...checkFileHeaders());
  }

  if (checkDocs) {
    allFailures.push(...checkGeneratedDocs());
  }

  console.log('═══════════════════════════════════════════════════════════════');

  if (allFailures.length) {
    console.log(`\n❌ RELEASE CHECK FAILED: ${allFailures.length} AI signature(s) found\n`);
    console.log('These patterns indicate AI-generated content that should not be');
    console.log('committed to the repository in release builds:\n');
    console.log('  • Co-authored-by trailers from AI tools');
    console.log('  • "Generated with/by AI" markers');
    console.log('  • "AI-generated" signatures\n');
    console.log('Remove these before releasing.\n');
    process.exit(1);
  }

  console.log('\n✅ RELEASE CHECK PASSED: No AI signatures found\n');
  process.exit(0);
}

if (require.main === module) {
  main();
}

module.exports = {
  checkCommitMessages,
  checkFileHeaders,
  checkGeneratedDocs,
  AI_SIGNATURE_PATTERNS,
};
